[config]

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR2 cava || true'

[templates.mpv]
input_path = '~/.config/matugen/templates/modernz.conf'
output_path = '~/.config/mpv/script-opts/modernz.conf'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/theme.conf'
post_hook = 'tmux source-file ~/.config/tmux/theme.conf'

[templates.fcitx5_theme_dark]
input_path = '~/.config/matugen/templates/fcitx5-dark.conf'
output_path = '~/.local/share/fcitx5/themes/matugen-dark/theme.conf'

[templates.fcitx5_highlight_dark]
input_path = '~/.config/matugen/templates/fcitx5-highlight.svg'
output_path = '~/.local/share/fcitx5/themes/matugen-dark/highlight.svg'

[templates.fcitx5_theme_light]
input_path = '~/.config/matugen/templates/fcitx5-light.conf'
output_path = '~/.local/share/fcitx5/themes/matugen-light/theme.conf'

[templates.fcitx5_highlight_light]
input_path = '~/.config/matugen/templates/fcitx5-highlight.svg'
output_path = '~/.local/share/fcitx5/themes/matugen-light/highlight.svg'
post_hook = 'fcitx5 -r -d'
