# Set true color
set -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Allows for faster key repetition
set -s escape-time 0

# Enable scroll mouse
set -g mouse on

# Constrain window size to maximum size.
setw -g aggressive-resize on

# Set vi-mode
setw -g mode-keys vi

# Set pane keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Escape to enter copy mode, v to selection, y to yank, p to paste
bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
unbind p
bind p pasteb

# Reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Open pane in current directory
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Configure catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg},reverse]█#[none]"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
