language=zh
seekbarfg_color={{colors.primary_fixed_dim.default.hex}}
seek_handle_color={{colors.primary_fixed_dim.default.hex}}
hover_effect_color={{colors.primary_fixed_dim.default.hex}}
nibble_color={{colors.primary_fixed_dim.default.hex}}
