set -gq @thm_mauve "{{colors.primary_fixed_dim.default.hex}}"
set -gq @thm_sapphire "{{dank16.color3.default.hex}}"
set -gq @catppuccin_host_color "#{@thm_mauve}"
set -gq @catppuccin_uptime_color "#{@thm_sapphire}"
set -gq @catppuccin_pane_border_style "fg={{colors.outline_variant.default.hex}}"
set -gq @catppuccin_pane_active_border_style "fg=#{@thm_mauve}"

set -wgF pane-border-style "#{E:@catppuccin_pane_border_style}"
set -wgF pane-active-border-style "#{E:@catppuccin_pane_active_border_style}"
