set -gq @thm_mauve "{{colors.primary_fixed_dim.default.hex}}"
set -gq @thm_sapphire "{{dank16.color3.default.hex}}"
set -gq @catppuccin_host_color "#{@thm_mauve}"
set -gq @catppuccin_uptime_color "#{@thm_sapphire}"
